name 'vape-php7'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures vape-php7'
long_description 'Installs/Configures vape-php7'
version '0.1.0'
